/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PjamProject1;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author activ
 */
public class PjamPong extends javax.swing.JFrame {
    private String keyW = "p1Up";
    private String keyS = "p2Down";
    private String keyUp = "p2Up";
    private String keyDown = "p2Down";
    /**
     * Creates new form PjamPong
     */
    public PjamPong() {
        initComponents();
        
        Action player1Up = new AbstractAction("p1Up") {
            @Override
            public void actionPerformed(ActionEvent e) {
               p1PongUp();
            }
        };
        
        Action player1Down = new AbstractAction("p1Down") {
            @Override
            public void actionPerformed(ActionEvent e) {
               p1PongDown();
            }
        };
        
        Action player2Up = new AbstractAction("p2Up") {
            @Override
            public void actionPerformed(ActionEvent e) {
               p2PongUp();
            }
        };
        
        Action player2Down = new AbstractAction("p2Down") {
            @Override
            public void actionPerformed(ActionEvent e) {
               p2PongDown();
            }
        };
           
        p1Pong.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("W"), keyW);
        p1Pong.getActionMap().put(keyW, player1Up);
        
        p1Pong.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("S"), keyS);
        p1Pong.getActionMap().put(keyS, player1Down);
        
        p2Pong.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(38, 0, false), keyUp);
        p2Pong.getActionMap().put(keyUp, player2Up);
        
        p2Pong.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(40, 0, false), keyDown);
        p2Pong.getActionMap().put(keyDown, player2Down);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1Pong = new javax.swing.JLabel();
        p2Pong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pjam Pong");
        setPreferredSize(new java.awt.Dimension(600, 400));

        p1Pong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PjamPong.png"))); // NOI18N

        p2Pong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PjamPong.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(p1Pong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p2Pong)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2Pong)
                    .addComponent(p1Pong))
                .addGap(235, 235, 235))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void p1PongUp(){
        int x = p1Pong.getX();
        int y = p1Pong.getY();
        //System.out.println("X: " + x + " Y: " + y);
        
        y = y - 5;
        
        if ( y >= 15 && y <= 310){
          p1Pong.setLocation(x, y);
        } else {
            System.out.println("Paddle can not travel further!");
        }
    }   
    public void p1PongDown(){
        int x = p1Pong.getX();
        int y = p1Pong.getY();
        //System.out.println("X: " + x + " Y: " + y);
        
        y = y + 5;
        
        if ( y >= 15 && y <= 310){
          p1Pong.setLocation(x, y);
        } else {
            System.out.println("Paddle can not travel further!");
        }
    } 
    
    public void p2PongUp(){
        int x = p2Pong.getX();
        int y = p2Pong.getY();
        //System.out.println("X: " + x + " Y: " + y);
        
        y = y - 5;
        
        if ( y >= 15 && y <= 310){
          p2Pong.setLocation(x, y);
        } else {
            System.out.println("Paddle can not travel further!");
        }
    }  
    
    public void p2PongDown(){
        int x = p2Pong.getX();
        int y = p2Pong.getY();
        //System.out.println("X: " + x + " Y: " + y);
        
        y = y + 5;
        
        if ( y >= 15 && y <= 310){
          p2Pong.setLocation(x, y);
        } else {
            System.out.println("Paddle can not travel further!");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PjamPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PjamPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PjamPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PjamPong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PjamPong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel p1Pong;
    private javax.swing.JLabel p2Pong;
    // End of variables declaration//GEN-END:variables
}
