
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nathan
 */
public class Pjam_Pong extends javax.swing.JFrame {
    boolean exit = false;
    //booleans that indicate how the ball is moving
    boolean ballGoingDown;
    boolean ballGoingRight;
    
    //adjustable speed value of ball (used for starting and stopping the game)
    int ballSpeed = 0;
    int paddleSpeed = 3;
    //adjustable x and y coordinate for pong ball
    //starts in the middle of the screen
    int ballx = 0;
    int bally = 0;
    
    int xBorder;
    int yBorder;
    
    int paddle1X = 0;
    int paddle1Y = 0;
    
    int paddle2X = 0;
    int paddle2Y = 0;
    
    PaddleDir p1Paddle;
    PaddleDir p2Paddle;
    
    /**
     * Creates new form Pjam_Pong along with basic setup of the frame
     */
    public Pjam_Pong() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.setTitle("Pong Game 1.0");
        this.setPreferredSize(new Dimension(1000, 800));
        pongScreen.setPreferredSize(new Dimension(710, 480));
        pongScreen.setLocation(150, 160);
        pongScreen.setBackground(Color.BLACK);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        startClock();
        
        //set panel location to middle of screen
        ballx = pongScreen.getWidth()/2;
        bally = pongScreen.getHeight()/2;
        
        //Set border of screen for ball to bounce off
        xBorder = pongScreen.getWidth() - 15;
        yBorder = pongScreen.getHeight() - 75;
        
        
        
        //start game with random direction
        randomDirection();
        moveBall();
        
        //set paddles to initial locations
        //Paddle 1
        paddle1X = pongScreen.getX()-100;
        paddle1Y = pongScreen.getHeight() / 2 - 30;
        
        //Paddle 2
        paddle2X = pongScreen.getWidth()-60;
        paddle2Y = pongScreen.getHeight() / 2 - 30;
    }
    
    //Paint method that draws a filled oval

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockLabel = new java.awt.Label();
        pongScreen = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                //Oval for pong ball right in the middle of the screen at first
                g.setColor(Color.WHITE);
                g.fillRect(ballx, bally, 15, 15);

                //Paddle for player 1 set on left side
                g.setColor(Color.RED);
                g.fillRect(paddle1X, paddle1Y, 15, 75);

                //Paddle for player 2 set on right side
                g.setColor(Color.BLUE);
                g.fillRect(paddle2X, paddle2Y, 15, 75);
            }
        };
        pongTitle = new java.awt.Label();
        startText = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        clockLabel.setBackground(java.awt.Color.white);
        clockLabel.setText("clock text");
        getContentPane().add(clockLabel);
        clockLabel.setBounds(730, 0, 241, 47);

        pongScreen.setBackground(java.awt.Color.black);
        pongScreen.setPreferredSize(new java.awt.Dimension(650, 450));
        pongScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pongScreenMouseClicked(evt);
            }
        });
        pongScreen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pongScreenKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pongScreenKeyReleased(evt);
            }
        });
        pongScreen.setLayout(null);
        getContentPane().add(pongScreen);
        pongScreen.setBounds(150, 160, 710, 480);

        pongTitle.setAlignment(java.awt.Label.CENTER);
        pongTitle.setBackground(java.awt.Color.white);
        pongTitle.setFont(new java.awt.Font("Bernard MT Condensed", 3, 48)); // NOI18N
        pongTitle.setForeground(java.awt.Color.pink);
        pongTitle.setText("Pong");
        getContentPane().add(pongTitle);
        pongTitle.setBounds(30, 30, 190, 90);

        startText.setAlignment(java.awt.Label.CENTER);
        startText.setBackground(java.awt.Color.white);
        startText.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        startText.setText("Press Spacebar to Start Game");
        getContentPane().add(startText);
        startText.setBounds(390, 70, 200, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pongScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pongScreenMouseClicked
        if (ballGoingRight)
            ballGoingRight = false;
        else
            ballGoingRight = true;
    }//GEN-LAST:event_pongScreenMouseClicked
    
    //Start game by pressing spacebar when ball is not moving (speed = 0)
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if (evt.getKeyChar() == ' ') {
            ballSpeed = 2;
            startText.setText("");
        }
        
        switch(evt.getKeyChar()) {
            //Player 1 Inputs
            case 'w':
                p1Paddle = PaddleDir.UP;
                break;
            case 's':
                p1Paddle = PaddleDir.DOWN;
                break;
            //Player 2 Inputs
            case 'i':
                p2Paddle = PaddleDir.UP;
                break;
            case 'k':
                p2Paddle = PaddleDir.DOWN;
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    private void pongScreenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pongScreenKeyPressed

    }//GEN-LAST:event_pongScreenKeyPressed

    private void pongScreenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pongScreenKeyReleased

    }//GEN-LAST:event_pongScreenKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        switch(evt.getKeyChar()) {
            //Player 1 Inputs
            case 'w':
                p1Paddle = PaddleDir.STOP;
                break;
            case 's':
                p1Paddle = PaddleDir.STOP;
                break;
            //Player 2 Inputs
            case 'i':
                p2Paddle = PaddleDir.STOP;
                break;
            case 'k':
                p2Paddle = PaddleDir.STOP;
                break;
        }
        repaint();
    }//GEN-LAST:event_formKeyReleased

    private void randomDirection() {
        int testX = (int) (Math.random() * 2) + 1;
        int testY = (int) (Math.random() * 2) + 1;
        System.out.println(testX);
        System.out.println(testY);
        if (testX == 1)
            ballGoingDown = false;
        else
            ballGoingDown = true;
        if (testY == 1)
            ballGoingRight = false;
        else
            ballGoingRight = true;
    }
    
    //Trying out enums to deal with paddle movement
    public enum PaddleDir {
        UP, DOWN, STOP
    }
    //Moving multiple paddles needs use of keyPressed and keyReleased
    //Method that deals with said idea
    private void paddleMovement() {
        if (p1Paddle == PaddleDir.STOP) {
            paddle1Y = paddle1Y;
        }
        if (p1Paddle == PaddleDir.UP) {
            paddle1Y -= paddleSpeed;
        }
        if (p1Paddle == PaddleDir.DOWN) {
            paddle1Y += paddleSpeed;
        }
        if (p2Paddle == PaddleDir.STOP) {
            paddle2Y = paddle2Y;
        }
        if (p2Paddle == PaddleDir.UP) {
            paddle2Y -= paddleSpeed;
        }
        if (p2Paddle == PaddleDir.DOWN) {
            paddle2Y += paddleSpeed;
        }
        if (paddle1Y <= 0)
            paddle1Y = 1;
        if (paddle1Y >= yBorder)
            paddle1Y = yBorder-1;     
        if (paddle2Y <= 0)
            paddle2Y = 1;
        if (paddle2Y >= yBorder)
            paddle2Y = yBorder-1;   
    }
    
    //Make the pong ball move automatically
    //Uses same idea as clock method
    private void moveBall() {
        Timer pongTimer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //ball behavior
                if (ballGoingRight)
                    ballx += ballSpeed;
                else
                    ballx -= ballSpeed;
                //if the ball is heading downwards
                if (ballGoingDown)
                    bally += ballSpeed;
                else
                    bally -= ballSpeed;
                //set "borders" to tell ball to bounce up and down (+15 for fine tuning probably due to borders)
                if (bally >= yBorder) {
                    ballGoingDown = false;
                }
                if (bally <= 0) {
                    ballGoingDown = true;
                }
                paddleMovement();
                repaint();
            }
        });
        pongTimer.start();
    }
    
    
    private void startClock() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                String dateTime = new Date().toString();
                
                clockLabel.setText(dateTime);
                
            }
        });
        timer.start();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pjam_Pong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pjam_Pong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pjam_Pong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pjam_Pong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pjam_Pong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label clockLabel;
    private javax.swing.JPanel pongScreen;
    private java.awt.Label pongTitle;
    private java.awt.Label startText;
    // End of variables declaration//GEN-END:variables
}


